tree_view/config/routes.rb
TreeView::Application.routes.draw do
  root :to => 'apparels#index'

  resources :apparels
end

tree_view/app/models/apparel.rb
class Apparel < ActiveRecord::Base
  has_ancestry

  attr_accessible :ancestry, :name, :parent_id

  validates_presence_of :name

  def self.search filter
    apparels =  if filter
                  Apparel.select('id, ancestry').where("name LIKE ? ", "%"+filter+"%").all
                else
                  Apparel.select('id, ancestry').all
                end

    apparel_path_ids = apparels.inject([]){|arr, item| arr|item.path_ids} # ids of nodes need to be shown
    roots = Apparel.where(:ancestry => nil).where(:id => apparel_path_ids).all

    [roots, apparel_path_ids]
  end
end

tree_view/app/controllers/apparels_controller.rb
class ApparelsController < ApplicationController
  def index
    @roots, @apparel_path_ids = Apparel.search(params[:filter])
  end

  def new
    @apparel = Apparel.new
    @parents = Apparel.select('id, name').all
  end

  def create
    @apparel = Apparel.new(params[:apparel])
    
    if @apparel.save
      redirect_to apparels_path
    else
      @parents = Apparel.select('id, name').all 

      render :action => :new
    end
  end
end

tree_view/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

tree_view/app/helpers/apparels_helper.rb
module ApparelsHelper
  def render_apparel(a, apparel_path_ids)
    render(:partial => 'apparel', :locals => {:apparel => a}) + a.children.select{|c| apparel_path_ids.include?(c.id)}.collect{|c| render_apparel(c, apparel_path_ids)}.join.html_safe
  end
end

tree_view/app/helpers/application_helper.rb
module ApplicationHelper
end

tree_view/app/views/apparels/_apparel.html.erb
<div class="apparel" style="padding-left: <%= apparel.depth * 20 %>px">
	<%= apparel.name %>
</div>

tree_view/app/views/apparels/index.html.erb
<%= form_tag(apparels_path, method: "GET") do %>
  <%= text_field_tag :filter, params[:filter] %>
  <%= button_tag :search %>
<% end %>
<div>
  <% if @roots.empty? %>
    No apparels were found.
  <% else %>
    <% @roots.each do |r| %>
      <%= render_apparel(r, @apparel_path_ids) %>
    <% end %>
  <% end %>
</div>
<div>
  <%= link_to 'Add item', new_apparel_path %>
</div>

tree_view/app/views/apparels/new.html.erb
<%= form_for @apparel do |f| %>
  <%= render "shared/error_messages", :target => @apparel %>
  <p>
    <%= f.label :name, :empty => true %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :parent_id, 'Parent' %>
    <%= f.select :parent_id, @parents.map{|p| [p.name, p.id]}, :include_blank => true %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

tree_view/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TreeView</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

tree_view/app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>  
  <div id="errorExplanation">  
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this <%= target.class.to_s.downcase %> from being saved:</h2>  
    <ul>  
    <% target.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>  
<% end %>  